version: '3.5'

services:

  react_learning:
    container_name: react_learning
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
